name: 프론트 운영 CD

on:
  push:
    branches: [deploy-fe]

jobs:
  buildAndDeploy:
    name: 프론트 운영 CD
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    env:
      working-directory: ./FE
      zip-name: airbnb-fe.zip

    steps:
      - name: 체크아웃 Github-Action
        uses: actions/checkout@v2

      - name: Docker Buildx 준비
        uses: docker/setup-buildx-action@v1

      - name: Github Container Registry 에 로그인
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_ACCESS_KEY }}
# working-directory: ${{ env.working-directory }}
      - name: 이미지 빌드 및 푸시
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./FE/Dockerfile
          push: true
          tags: 
            ghcr.io/${{ github.repository_owner }}/airbnb-fe:latest
      
      - name: airbnb-deploy.zip 생성
        run: zip -r ./${{ env.zip-name }} ./scripts ./appspec.yml
        working-directory: ${{ env.working-directory }}

      - name: AWS Credential 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: AWS S3 로 업로드
        run: aws s3 cp --region ap-northeast-2 ./${{ env.zip-name }} s3://airbnb-s3-bucket-deploy/${{ env.zip-name }}
        working-directory: ${{ env.working-directory }}

      - name: AWS CodeDeploy 배포 실행
        run: aws deploy create-deployment 
          --application-name airbnb-deploy
          --deployment-group airbnb-fe-dg
          --s3-location bucket=airbnb-s3-bucket-deploy,key=${{ env.zip-name }},bundleType=zip
